In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import openpyxl as op

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_excel(r'/Users/menna/Python/EDA/Final Project/Dataset/payroll_sample.xlsx')
df

,Employee ID,Serial Number,Employee Name,Job Title,Department,Hire Date,Date of Birth,Age,Last Working Day (If Terminated),Termination Reason,Working Days,2025 Salary,January 2026 Raise,Additional Raise During 2026,January 2026 Raise Rate,Gross Salary,Daily Wage,Hourly Wage,Monthly Salary,Basic Salary,Clothing Allowance,Transportation Allowance,Housing Allowance,Meal Allowance,Total Allowances,Variable Allowances,Business Trip Allowance,Additional Allowance,Bonuses and Incentives,Other Earnings,Total Variable Pay,Total Salary,Absence Days,Absence Penalty (Days),Absence Deduction Amount,Statutory Penalty (Days),Statutory Penalty Amount,Administrative Penalty (Days),Administrative Penalty Amount,Other Monetary Penalties,Total Penalties,Empty Field 1,Month,Net Salary,Empty Field 2
0,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaN,NaN,30.0,6750.0,810.0,0.0,0.12,8619.12,287.30,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,0.0,0.0,100.0,0.0,0.0,100.0,8719.12,0,0,0,0.0,0,0.0,0,0.0,0,NaN,01/2026,7557.22,NaN
1,1002.0,2.0,Mohamed Mohamed,Quality Officer,Quality,2025-02-25,1979-10-23,46.0,NaN,NaN,30.0,7750.0,775.0,232.5,0.10,7649.59,254.99,31.87,7649.59,5999.59,150.0,400.0,500.0,600.0,1650.0,500.0,250.0,150.0,0.0,0.0,900.0,8549.59,0,0,0,0.0,0,0.0,0,100.0,0,NaN,01/2026,7029.63,NaN
2,1003.0,3.0,Heba Adel,Sales Representative,Sales,2023-11-01,1990-02-24,35.0,NaN,NaN,30.0,6750.0,675.0,0.0,0.10,7328.64,244.29,30.54,7328.64,5228.64,200.0,600.0,1000.0,300.0,2100.0,200.0,0.0,0.0,500.0,100.0,800.0,8128.64,0,0,0,0.0,0,0.0,0,100.0,0,NaN,01/2026,7778.64,NaN
3,1004.0,4.0,Mariam Elsayed,Logistics Officer,Logistics,2022-07-24,1976-12-22,49.0,NaN,NaN,30.0,20250.0,0.0,0.0,0.00,17071.77,569.06,71.13,17071.77,14871.77,150.0,750.0,1000.0,300.0,2200.0,300.0,150.0,100.0,0.0,0.0,550.0,17621.77,0,0,0,0.0,0,0.0,0,100.0,0,NaN,01/2026,17521.77,NaN
4,1005.0,5.0,Mostafa Mansour,Maintenance Engineer,Maintenance,2025-04-13,1997-01-30,29.0,NaN,NaN,30.0,8000.0,0.0,240.0,0.00,7278.15,242.60,30.32,7278.15,6028.15,250.0,500.0,0.0,500.0,1250.0,0.0,400.0,0.0,1000.0,100.0,1500.0,8778.15,0,0,0,0.0,0,0.0,0,0.0,0,NaN,01/2026,7750.35,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1971,1251.0,233.0,Heba Adel,Maintenance Engineer,Maintenance,2026-09-23,1988-01-04,38.0,NaN,NaN,8.0,15000.0,750.0,450.0,0.05,14472.31,482.41,60.30,14472.31,12322.31,300.0,500.0,750.0,600.0,2150.0,100.0,0.0,250.0,1000.0,50.0,1400.0,5259.28,4,4,6666٫666667,0.0,0,0.0,0,0.0,6666٫666667,NaN,09/2026,5259.28,NaN
1972,1223.0,216.0,Mostafa Fouad,Personnel Affairs Specialist,Human Resources,2026-05-27,2000-12-23,25.0,NaN,NaN,4.0,8000.0,560.0,400.0,0.07,7054.13,235.14,29.39,7054.13,5954.13,300.0,400.0,0.0,400.0,1100.0,300.0,0.0,100.0,500.0,100.0,1000.0,1940.55,0,0,0,1.0,4000,0.0,0,100.0,4000,NaN,05/2026,1035.13,NaN
1973,1253.0,235.0,Ahmed Mahmoud,Warehouse Supervisor,Warehousing,2026-09-02,1977-12-20,48.0,NaN,NaN,29.0,11250.0,787.5,0.0,0.07,10478.93,349.30,43.66,10478.93,8678.93,150.0,600.0,750.0,300.0,1800.0,200.0,0.0,150.0,0.0,0.0,350.0,10479.63,0,0,0,0.0,0,0.0,0,150.0,0,NaN,09/2026,9980.33,NaN
1974,1254.0,236.0,Iman Samir,Quality Officer,Quality,2026-09-30,1984-01-27,42.0,NaN,NaN,1.0,21000.0,1680.0,630.0,0.08,17376.10,579.20,72.40,17376.10,16426.10,150.0,400.0,0.0,400.0,950.0,500.0,0.0,250.0,500.0,0.0,1250.0,1829.20,0,0,0,0.0,0,0.0,0,0.0,0,NaN,09/2026,1729.20,NaN
1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0,0,0.0,0,NaN,0,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1976 entries, 0 to 1975
Data columns (total 45 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Employee ID                       1975 non-null   float64
 1   Serial Number                     1975 non-null   float64
 2   Employee Name                     1975 non-null   str
 3   Job Title                         1975 non-null   str
 4   Department                        1975 non-null   str
 5   Hire Date                         1975 non-null   str
 6   Date of Birth                     1975 non-null   str
 7   Age                               1975 non-null   float64
 8   Last Working Day (If Terminated)  20 non-null     str
 9   Termination Reason                20 non-null     str
 10  Working Days                      1975 non-null   float64
 11  2025 Salary                       1975 non-null   float64
 12  January 2026 Raise                1975 non-null   float64
 13  Additional Raise During 2026      1975 non-null   float64
 14  January 2026 Raise Rate           1975 non-null   float64
 15  Gross Salary                      1975 non-null   float64
 16  Daily Wage                        1975 non-null   float64
 17  Hourly Wage                       1975 non-null   float64
 18  Monthly Salary                    1975 non-null   float64
 19  Basic Salary                      1975 non-null   float64
 20  Clothing Allowance                1975 non-null   float64
 21  Transportation Allowance          1975 non-null   float64
 22  Housing Allowance                 1975 non-null   float64
 23  Meal Allowance                    1975 non-null   float64
 24  Total Allowances                  1975 non-null   float64
 25  Variable Allowances               1975 non-null   float64
 26  Business Trip Allowance           1975 non-null   float64
 27  Additional Allowance              1975 non-null   float64
 28  Bonuses and Incentives            1975 non-null   float64
 29  Other Earnings                    1975 non-null   float64
 30  Total Variable Pay                1975 non-null   float64
 31  Total Salary                      1975 non-null   float64
 32  Absence Days                      1976 non-null   int64
 33  Absence Penalty (Days)            1976 non-null   int64
 34  Absence Deduction Amount          1976 non-null   object
 35  Statutory Penalty (Days)          1976 non-null   float64
 36  Statutory Penalty Amount          1976 non-null   object
 37  Administrative Penalty (Days)     1976 non-null   float64
 38  Administrative Penalty Amount     1976 non-null   object
 39  Other Monetary Penalties          1975 non-null   float64
 40  Total Penalties                   1976 non-null   object
 41  Empty Field 1                     0 non-null      float64
 42  Month                             1975 non-null   str
 43  Net Salary                        1975 non-null   float64
 44  Empty Field 2                     0 non-null      float64
dtypes: float64(31), int64(2), object(4), str(8)
memory usage: 829.5+ KB

In [5]:
df.describe()

,Employee ID,Serial Number,Age,Working Days,2025 Salary,January 2026 Raise,Additional Raise During 2026,January 2026 Raise Rate,Gross Salary,Daily Wage,Hourly Wage,Monthly Salary,Basic Salary,Clothing Allowance,Transportation Allowance,Housing Allowance,Meal Allowance,Total Allowances,Variable Allowances,Business Trip Allowance,Additional Allowance,Bonuses and Incentives,Other Earnings,Total Variable Pay,Total Salary,Absence Days,Absence Penalty (Days),Statutory Penalty (Days),Administrative Penalty (Days),Other Monetary Penalties,Empty Field 1,Net Salary,Empty Field 2
count,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1976.000000,1976.000000,1976.000000,1976.000000,1975.000000,0.0,1975.000000,0.0
mean,1115.695190,110.578734,39.256203,29.396962,13877.974684,925.288608,373.029114,0.068192,12899.468846,429.982253,53.747610,12899.468846,10827.063782,232.278481,627.594937,775.063291,437.468354,2072.405063,154.886076,135.822785,153.974684,361.113924,68.050633,873.848101,13513.792754,0.130061,0.101215,0.035425,0.093244,48.860759,NaN,12653.967782,NaN
std,66.525481,63.977594,9.291638,3.552813,4641.182328,606.131610,425.930836,0.037732,3670.396696,122.346444,15.293269,3670.396696,3646.008867,54.390548,177.817564,505.671666,114.428543,550.490744,174.908211,152.284259,143.759584,372.675878,72.911637,468.329153,3936.412021,0.785816,0.570923,0.202072,0.504979,57.139410,NaN,3836.636386,NaN
min,1001.000000,1.000000,23.000000,1.000000,6500.000000,0.000000,0.000000,0.000000,6132.440000,204.410000,25.550000,6132.440000,4775.080000,150.000000,400.000000,0.000000,300.000000,850.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,673.720000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,NaN
25%,1059.000000,55.000000,31.000000,30.000000,10000.000000,560.000000,0.000000,0.050000,9628.050000,320.940000,40.120000,9628.050000,7730.510000,200.000000,500.000000,500.000000,300.000000,1700.000000,0.000000,0.000000,0.000000,0.000000,0.000000,500.000000,10319.005000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,9684.285000,NaN
50%,1115.000000,110.000000,39.000000,30.000000,13750.000000,875.000000,247.500000,0.070000,12728.200000,424.270000,53.030000,12728.200000,10628.200000,250.000000,600.000000,750.000000,400.000000,2100.000000,100.000000,150.000000,150.000000,300.000000,50.000000,850.000000,13571.950000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,12584.240000,NaN
75%,1172.000000,165.000000,47.000000,30.000000,17500.000000,1347.500000,662.500000,0.100000,15950.085000,531.670000,66.460000,15950.085000,13834.630000,300.000000,750.000000,1000.000000,500.000000,2500.000000,300.000000,250.000000,250.000000,750.000000,100.000000,1200.000000,16682.155000,0.000000,0.000000,0.000000,0.000000,100.000000,NaN,15522.970000,NaN
max,1254.000000,237.000000,56.000000,30.000000,22000.000000,2610.000000,1540.000000,0.120000,21388.400000,712.950000,89.120000,21388.400000,19390.980000,300.000000,900.000000,1500.000000,600.000000,3150.000000,500.000000,400.000000,400.000000,1000.000000,200.000000,2500.000000,23338.400000,15.000000,10.000000,3.000000,5.000000,200.000000,NaN,23238.400000,NaN

In [6]:
df.isna().sum()

Employee ID                            1
Serial Number                          1
Employee Name                          1
Job Title                              1
Department                             1
Hire Date                              1
Date of Birth                          1
Age                                    1
Last Working Day (If Terminated)    1956
Termination Reason                  1956
Working Days                           1
2025 Salary                            1
January 2026 Raise                     1
Additional Raise During 2026           1
January 2026 Raise Rate                1
Gross Salary                           1
Daily Wage                             1
Hourly Wage                            1
Monthly Salary                         1
Basic Salary                           1
Clothing Allowance                     1
Transportation Allowance               1
Housing Allowance                      1
Meal Allowance                         1
Total Allowances                       1
Variable Allowances                    1
Business Trip Allowance                1
Additional Allowance                   1
Bonuses and Incentives                 1
Other Earnings                         1
Total Variable Pay                     1
Total Salary                           1
Absence Days                           0
Absence Penalty (Days)                 0
Absence Deduction Amount               0
Statutory Penalty (Days)               0
Statutory Penalty Amount               0
Administrative Penalty (Days)          0
Administrative Penalty Amount          0
Other Monetary Penalties               1
Total Penalties                        0
Empty Field 1                       1976
Month                                  1
Net Salary                             1
Empty Field 2                       1976
dtype: int64

In [7]:
df = df.dropna(subset=['Employee ID'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1975 entries, 0 to 1974
Data columns (total 45 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Employee ID                       1975 non-null   float64
 1   Serial Number                     1975 non-null   float64
 2   Employee Name                     1975 non-null   str
 3   Job Title                         1975 non-null   str
 4   Department                        1975 non-null   str
 5   Hire Date                         1975 non-null   str
 6   Date of Birth                     1975 non-null   str
 7   Age                               1975 non-null   float64
 8   Last Working Day (If Terminated)  20 non-null     str
 9   Termination Reason                20 non-null     str
 10  Working Days                      1975 non-null   float64
 11  2025 Salary                       1975 non-null   float64
 12  January 2026 Raise                1975 non-null   float64
 13  Additional Raise During 2026      1975 non-null   float64
 14  January 2026 Raise Rate           1975 non-null   float64
 15  Gross Salary                      1975 non-null   float64
 16  Daily Wage                        1975 non-null   float64
 17  Hourly Wage                       1975 non-null   float64
 18  Monthly Salary                    1975 non-null   float64
 19  Basic Salary                      1975 non-null   float64
 20  Clothing Allowance                1975 non-null   float64
 21  Transportation Allowance          1975 non-null   float64
 22  Housing Allowance                 1975 non-null   float64
 23  Meal Allowance                    1975 non-null   float64
 24  Total Allowances                  1975 non-null   float64
 25  Variable Allowances               1975 non-null   float64
 26  Business Trip Allowance           1975 non-null   float64
 27  Additional Allowance              1975 non-null   float64
 28  Bonuses and Incentives            1975 non-null   float64
 29  Other Earnings                    1975 non-null   float64
 30  Total Variable Pay                1975 non-null   float64
 31  Total Salary                      1975 non-null   float64
 32  Absence Days                      1975 non-null   int64
 33  Absence Penalty (Days)            1975 non-null   int64
 34  Absence Deduction Amount          1975 non-null   object
 35  Statutory Penalty (Days)          1975 non-null   float64
 36  Statutory Penalty Amount          1975 non-null   object
 37  Administrative Penalty (Days)     1975 non-null   float64
 38  Administrative Penalty Amount     1975 non-null   object
 39  Other Monetary Penalties          1975 non-null   float64
 40  Total Penalties                   1975 non-null   object
 41  Empty Field 1                     0 non-null      float64
 42  Month                             1975 non-null   str
 43  Net Salary                        1975 non-null   float64
 44  Empty Field 2                     0 non-null      float64
dtypes: float64(31), int64(2), object(4), str(8)
memory usage: 829.2+ KB

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe(include= 'object')

/var/folders/pg/49nnzmms37n90hk92kwrnvbh0000gn/T/ipykernel_3473/3793228563.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include= 'object')

,Employee Name,Job Title,Department,Hire Date,Date of Birth,Last Working Day (If Terminated),Termination Reason,Absence Deduction Amount,Statutory Penalty Amount,Administrative Penalty Amount,Total Penalties,Month
count,1975,1975,1975,1975,1975,20,20,1975,1975,1975,1975,1975
unique,194,14,12,236,249,20,5,50,56,58,146,9
top,Ibrahim Abdullah,Branch Manager,Human Resources,2026-02-20,1995-05-22,2026-02-10,Resignation,0,0,0,0,08/2026
freq,33,214,259,24,18,1,6,1861,1882,1870,1637,237

In [10]:
df['Hire Date'] = pd.to_datetime(df['Hire Date'])
df['Date of Birth'] = pd.to_datetime(df['Date of Birth'])
df['Last Working Day (If Terminated)'] = pd.to_datetime(df['Last Working Day (If Terminated)'])
df['Month'] = pd.to_datetime(df['Month'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1975 entries, 0 to 1974
Data columns (total 45 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Employee ID                       1975 non-null   float64
 1   Serial Number                     1975 non-null   float64
 2   Employee Name                     1975 non-null   str
 3   Job Title                         1975 non-null   str
 4   Department                        1975 non-null   str
 5   Hire Date                         1975 non-null   datetime64[us]
 6   Date of Birth                     1975 non-null   datetime64[us]
 7   Age                               1975 non-null   float64
 8   Last Working Day (If Terminated)  20 non-null     datetime64[us]
 9   Termination Reason                20 non-null     str
 10  Working Days                      1975 non-null   float64
 11  2025 Salary                       1975 non-null   float64
 12  January 2026 Raise                1975 non-null   float64
 13  Additional Raise During 2026      1975 non-null   float64
 14  January 2026 Raise Rate           1975 non-null   float64
 15  Gross Salary                      1975 non-null   float64
 16  Daily Wage                        1975 non-null   float64
 17  Hourly Wage                       1975 non-null   float64
 18  Monthly Salary                    1975 non-null   float64
 19  Basic Salary                      1975 non-null   float64
 20  Clothing Allowance                1975 non-null   float64
 21  Transportation Allowance          1975 non-null   float64
 22  Housing Allowance                 1975 non-null   float64
 23  Meal Allowance                    1975 non-null   float64
 24  Total Allowances                  1975 non-null   float64
 25  Variable Allowances               1975 non-null   float64
 26  Business Trip Allowance           1975 non-null   float64
 27  Additional Allowance              1975 non-null   float64
 28  Bonuses and Incentives            1975 non-null   float64
 29  Other Earnings                    1975 non-null   float64
 30  Total Variable Pay                1975 non-null   float64
 31  Total Salary                      1975 non-null   float64
 32  Absence Days                      1975 non-null   int64
 33  Absence Penalty (Days)            1975 non-null   int64
 34  Absence Deduction Amount          1975 non-null   object
 35  Statutory Penalty (Days)          1975 non-null   float64
 36  Statutory Penalty Amount          1975 non-null   object
 37  Administrative Penalty (Days)     1975 non-null   float64
 38  Administrative Penalty Amount     1975 non-null   object
 39  Other Monetary Penalties          1975 non-null   float64
 40  Total Penalties                   1975 non-null   object
 41  Empty Field 1                     0 non-null      float64
 42  Month                             1975 non-null   datetime64[us]
 43  Net Salary                        1975 non-null   float64
 44  Empty Field 2                     0 non-null      float64
dtypes: datetime64[us](4), float64(31), int64(2), object(4), str(4)
memory usage: 775.9+ KB

/var/folders/pg/49nnzmms37n90hk92kwrnvbh0000gn/T/ipykernel_3473/182400343.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Month'] = pd.to_datetime(df['Month'])

In [11]:
df.drop(columns=['Empty Field 1' , 'Empty Field 2'] , inplace=True)
df

,Employee ID,Serial Number,Employee Name,Job Title,Department,Hire Date,Date of Birth,Age,Last Working Day (If Terminated),Termination Reason,Working Days,2025 Salary,January 2026 Raise,Additional Raise During 2026,January 2026 Raise Rate,Gross Salary,Daily Wage,Hourly Wage,Monthly Salary,Basic Salary,Clothing Allowance,Transportation Allowance,Housing Allowance,Meal Allowance,Total Allowances,Variable Allowances,Business Trip Allowance,Additional Allowance,Bonuses and Incentives,Other Earnings,Total Variable Pay,Total Salary,Absence Days,Absence Penalty (Days),Absence Deduction Amount,Statutory Penalty (Days),Statutory Penalty Amount,Administrative Penalty (Days),Administrative Penalty Amount,Other Monetary Penalties,Total Penalties,Month,Net Salary
0,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaT,NaN,30.0,6750.0,810.0,0.0,0.12,8619.12,287.30,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,0.0,0.0,100.0,0.0,0.0,100.0,8719.12,0,0,0,0.0,0,0.0,0,0.0,0,2026-01-01,7557.22
1,1002.0,2.0,Mohamed Mohamed,Quality Officer,Quality,2025-02-25,1979-10-23,46.0,NaT,NaN,30.0,7750.0,775.0,232.5,0.10,7649.59,254.99,31.87,7649.59,5999.59,150.0,400.0,500.0,600.0,1650.0,500.0,250.0,150.0,0.0,0.0,900.0,8549.59,0,0,0,0.0,0,0.0,0,100.0,0,2026-01-01,7029.63
2,1003.0,3.0,Heba Adel,Sales Representative,Sales,2023-11-01,1990-02-24,35.0,NaT,NaN,30.0,6750.0,675.0,0.0,0.10,7328.64,244.29,30.54,7328.64,5228.64,200.0,600.0,1000.0,300.0,2100.0,200.0,0.0,0.0,500.0,100.0,800.0,8128.64,0,0,0,0.0,0,0.0,0,100.0,0,2026-01-01,7778.64
3,1004.0,4.0,Mariam Elsayed,Logistics Officer,Logistics,2022-07-24,1976-12-22,49.0,NaT,NaN,30.0,20250.0,0.0,0.0,0.00,17071.77,569.06,71.13,17071.77,14871.77,150.0,750.0,1000.0,300.0,2200.0,300.0,150.0,100.0,0.0,0.0,550.0,17621.77,0,0,0,0.0,0,0.0,0,100.0,0,2026-01-01,17521.77
4,1005.0,5.0,Mostafa Mansour,Maintenance Engineer,Maintenance,2025-04-13,1997-01-30,29.0,NaT,NaN,30.0,8000.0,0.0,240.0,0.00,7278.15,242.60,30.32,7278.15,6028.15,250.0,500.0,0.0,500.0,1250.0,0.0,400.0,0.0,1000.0,100.0,1500.0,8778.15,0,0,0,0.0,0,0.0,0,0.0,0,2026-01-01,7750.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,1250.0,232.0,Aya Morad,Quality Officer,Quality,2026-08-30,1976-07-29,50.0,NaT,NaN,30.0,21500.0,0.0,0.0,0.00,16769.03,558.97,69.87,16769.03,15769.03,200.0,500.0,0.0,300.0,1000.0,0.0,0.0,0.0,1000.0,50.0,1050.0,17819.03,1,1,1666٫666667,0.0,0,0.0,0,150.0,1666٫666667,2026-09-01,17469.03
1971,1251.0,233.0,Heba Adel,Maintenance Engineer,Maintenance,2026-09-23,1988-01-04,38.0,NaT,NaN,8.0,15000.0,750.0,450.0,0.05,14472.31,482.41,60.30,14472.31,12322.31,300.0,500.0,750.0,600.0,2150.0,100.0,0.0,250.0,1000.0,50.0,1400.0,5259.28,4,4,6666٫666667,0.0,0,0.0,0,0.0,6666٫666667,2026-09-01,5259.28
1972,1223.0,216.0,Mostafa Fouad,Personnel Affairs Specialist,Human Resources,2026-05-27,2000-12-23,25.0,NaT,NaN,4.0,8000.0,560.0,400.0,0.07,7054.13,235.14,29.39,7054.13,5954.13,300.0,400.0,0.0,400.0,1100.0,300.0,0.0,100.0,500.0,100.0,1000.0,1940.55,0,0,0,1.0,4000,0.0,0,100.0,4000,2026-05-01,1035.13
1973,1253.0,235.0,Ahmed Mahmoud,Warehouse Supervisor,Warehousing,2026-09-02,1977-12-20,48.0,NaT,NaN,29.0,11250.0,787.5,0.0,0.07,10478.93,349.30,43.66,10478.93,8678.93,150.0,600.0,750.0,300.0,1800.0,200.0,0.0,150.0,0.0,0.0,350.0,10479.63,0,0,0,0.0,0,0.0,0,150.0,0,2026-09-01,9980.33
1974,1254.0,236.0,Iman Samir,Quality Officer,Quality,2026-09-30,1984-01-27,42.0,NaT,NaN,1.0,21000.0,1680.0,630.0,0.08,17376.10,579.20,72.40,17376.10,16426.10,150.0,400.0,0.0,400.0,950.0,500.0,0.0,250.0,500.0,0.0,1250.0,1829.20,0,0,0,0.0,0,0.0,0,0.0,0,2026-09-01,1729.20

In [12]:
num_col =df.select_dtypes(include = 'number').columns.drop(['Employee ID', 'Serial Number'])
num_col

Index(['Age', 'Working Days', '2025 Salary', 'January 2026 Raise',
       'Additional Raise During 2026', 'January 2026 Raise Rate',
       'Gross Salary', 'Daily Wage', 'Hourly Wage', 'Monthly Salary',
       'Basic Salary', 'Clothing Allowance', 'Transportation Allowance',
       'Housing Allowance', 'Meal Allowance', 'Total Allowances',
       'Variable Allowances', 'Business Trip Allowance',
       'Additional Allowance', 'Bonuses and Incentives', 'Other Earnings',
       'Total Variable Pay', 'Total Salary', 'Absence Days',
       'Absence Penalty (Days)', 'Statutory Penalty (Days)',
       'Administrative Penalty (Days)', 'Other Monetary Penalties',
       'Net Salary'],
      dtype='str')

In [13]:
for col in num_col:
    px.histogram(data_frame= df , x= col , title= col).show()
    px.box(data_frame= df , x=col , title=col).show()

### Feature Engineering

In [16]:
df['Daily Wage']=df['Gross Salary']/30
df['2025 Salary'] = df['Gross Salary']-(df['January 2026 Raise']+df['Additional Raise During 2026'])
df['January 2026 Raise Rate'] = round((df['January 2026 Raise']+df['Additional Raise During 2026']) / df['2025 Salary'],2)
df

,Employee ID,Serial Number,Employee Name,Job Title,Department,Hire Date,Date of Birth,Age,Last Working Day (If Terminated),Termination Reason,Working Days,2025 Salary,January 2026 Raise,Additional Raise During 2026,January 2026 Raise Rate,Gross Salary,Daily Wage,Hourly Wage,Monthly Salary,Basic Salary,Clothing Allowance,Transportation Allowance,Housing Allowance,Meal Allowance,Total Allowances,Variable Allowances,Business Trip Allowance,Additional Allowance,Bonuses and Incentives,Other Earnings,Total Variable Pay,Total Salary,Absence Days,Absence Penalty (Days),Absence Deduction Amount,Statutory Penalty (Days),Statutory Penalty Amount,Administrative Penalty (Days),Administrative Penalty Amount,Other Monetary Penalties,Total Penalties,Month,Net Salary
0,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaT,NaN,30.0,7809.12,810.0,0.0,0.10,8619.12,287.304000,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,0.0,0.0,100.0,0.0,0.0,100.0,8719.12,0,0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,2026-01-01,8719.120000
1,1002.0,2.0,Mohamed Mohamed,Quality Officer,Quality,2025-02-25,1979-10-23,46.0,NaT,NaN,30.0,6642.09,775.0,232.5,0.15,7649.59,254.986333,31.87,7649.59,5999.59,150.0,400.0,500.0,600.0,1650.0,500.0,250.0,150.0,0.0,0.0,900.0,8549.59,0,0,0.000000,0.0,0.000000,0.0,0.0,100.0,100.000000,2026-01-01,8449.590000
2,1003.0,3.0,Heba Adel,Sales Representative,Sales,2023-11-01,1990-02-24,35.0,NaT,NaN,30.0,6653.64,675.0,0.0,0.10,7328.64,244.288000,30.54,7328.64,5228.64,200.0,600.0,1000.0,300.0,2100.0,200.0,0.0,0.0,500.0,100.0,800.0,8128.64,0,0,0.000000,0.0,0.000000,0.0,0.0,100.0,100.000000,2026-01-01,8028.640000
3,1004.0,4.0,Mariam Elsayed,Logistics Officer,Logistics,2022-07-24,1976-12-22,49.0,NaT,NaN,30.0,17071.77,0.0,0.0,0.00,17071.77,569.059000,71.13,17071.77,14871.77,150.0,750.0,1000.0,300.0,2200.0,300.0,150.0,100.0,0.0,0.0,550.0,17621.77,0,0,0.000000,0.0,0.000000,0.0,0.0,100.0,100.000000,2026-01-01,17521.770000
4,1005.0,5.0,Mostafa Mansour,Maintenance Engineer,Maintenance,2025-04-13,1997-01-30,29.0,NaT,NaN,30.0,7038.15,0.0,240.0,0.03,7278.15,242.605000,30.32,7278.15,6028.15,250.0,500.0,0.0,500.0,1250.0,0.0,400.0,0.0,1000.0,100.0,1500.0,8778.15,0,0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,2026-01-01,8778.150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,1250.0,232.0,Aya Morad,Quality Officer,Quality,2026-08-30,1976-07-29,50.0,NaT,NaN,30.0,16769.03,0.0,0.0,0.00,16769.03,558.967667,69.87,16769.03,15769.03,200.0,500.0,0.0,300.0,1000.0,0.0,0.0,0.0,1000.0,50.0,1050.0,17819.03,1,1,1117.935333,0.0,0.000000,0.0,0.0,150.0,1267.935333,2026-09-01,16551.094667
1971,1251.0,233.0,Heba Adel,Maintenance Engineer,Maintenance,2026-09-23,1988-01-04,38.0,NaT,NaN,8.0,13272.31,750.0,450.0,0.09,14472.31,482.410333,60.30,14472.31,12322.31,300.0,500.0,750.0,600.0,2150.0,100.0,0.0,250.0,1000.0,50.0,1400.0,15872.31,4,4,3859.282667,0.0,0.000000,0.0,0.0,0.0,3859.282667,2026-09-01,12013.027333
1972,1223.0,216.0,Mostafa Fouad,Personnel Affairs Specialist,Human Resources,2026-05-27,2000-12-23,25.0,NaT,NaN,4.0,6094.13,560.0,400.0,0.16,7054.13,235.137667,29.39,7054.13,5954.13,300.0,400.0,0.0,400.0,1100.0,300.0,0.0,100.0,500.0,100.0,1000.0,8054.13,0,0,0.000000,1.0,235.137667,0.0,0.0,100.0,335.137667,2026-05-01,7718.992333
1973,1253.0,235.0,Ahmed Mahmoud,Warehouse Supervisor,Warehousing,2026-09-02,1977-12-20,48.0,NaT,NaN,29.0,9691.43,787.5,0.0,0.08,10478.93,349.297667,43.66,10478.93,8678.93,150.0,600.0,750.0,300.0,1800.0,200.0,0.0,150.0,0.0,0.0,350.0,10828.93,0,0,0.000000,0.0,0.000000,0.0,0.0,150.0,150.000000,2026-09-01,10678.930000
1974,1254.0,236.0,Iman Samir,Quality Officer,Quality,2026-09-30,1984-01-27,42.0,NaT,NaN,1.0,15066.10,1680.0,630.0,0.15,17376.10,579.203333,72.40,17376.10,16426.10,150.0,400.0,0.0,400.0,950.0,500.0,0.0,250.0,500.0,0.0,1250.0,18626.10,0,0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,2026-09-01,18626.100000

In [ ]:

df['Absence Deduction Amount']=(df['Absence Penalty (Days)']+df['Absence Days'])*df['Daily Wage']
df['Statutory Penalty Amount']=pd.to_numeric(df['Statutory Penalty (Days)'])*df['Daily Wage']
df['Administrative Penalty Amount']=df['Administrative Penalty (Days)']*df['Daily Wage']
df['Total Penalties'] = df['Absence Deduction Amount'] + df['Statutory Penalty Amount']+df['Administrative Penalty Amount']+df['Other Monetary Penalties']
df['Total Salary'] = df['Gross Salary']+df['Variable Allowances']+df['Business Trip Allowance']+df['Additional Allowance']+df['Bonuses and Incentives']+df['Other Earnings']
df['Net Salary'] = df['Total Salary']-df['Total Penalties']

df

In [17]:
df['Salaries Month'] = df['Month'].dt.month_name()
df['Salaries Month']

0         January
1         January
2         January
3         January
4         January
          ...
1970    September
1971    September
1972          May
1973    September
1974    September
Name: Salaries Month, Length: 1975, dtype: str

In [18]:
df['Months']=df['Hire Date'].dt.month
df['Months']

0        8
1        2
2       11
3        7
4        4
        ..
1970     8
1971     9
1972     5
1973     9
1974     9
Name: Months, Length: 1975, dtype: int32

In [30]:
df['Month_num'] = df['Month'].dt.month
df['Month_num']

0       1
1       1
2       1
3       1
4       1
       ..
1970    9
1971    9
1972    5
1973    9
1974    9
Name: Month_num, Length: 1975, dtype: int32

### Data Analysis

In [19]:
df.head()

,Employee ID,Serial Number,Employee Name,Job Title,Department,Hire Date,Date of Birth,Age,Last Working Day (If Terminated),Termination Reason,Working Days,2025 Salary,January 2026 Raise,Additional Raise During 2026,January 2026 Raise Rate,Gross Salary,Daily Wage,Hourly Wage,Monthly Salary,Basic Salary,Clothing Allowance,Transportation Allowance,Housing Allowance,Meal Allowance,Total Allowances,Variable Allowances,Business Trip Allowance,Additional Allowance,Bonuses and Incentives,Other Earnings,Total Variable Pay,Total Salary,Absence Days,Absence Penalty (Days),Absence Deduction Amount,Statutory Penalty (Days),Statutory Penalty Amount,Administrative Penalty (Days),Administrative Penalty Amount,Other Monetary Penalties,Total Penalties,Month,Net Salary,Salaries Month,Months
0,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaT,NaN,30.0,7809.12,810.0,0.0,0.10,8619.12,287.304000,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,0.0,0.0,100.0,0.0,0.0,100.0,8719.12,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-01-01,8719.12,January,8
1,1002.0,2.0,Mohamed Mohamed,Quality Officer,Quality,2025-02-25,1979-10-23,46.0,NaT,NaN,30.0,6642.09,775.0,232.5,0.15,7649.59,254.986333,31.87,7649.59,5999.59,150.0,400.0,500.0,600.0,1650.0,500.0,250.0,150.0,0.0,0.0,900.0,8549.59,0,0,0.0,0.0,0.0,0.0,0.0,100.0,100.0,2026-01-01,8449.59,January,2
2,1003.0,3.0,Heba Adel,Sales Representative,Sales,2023-11-01,1990-02-24,35.0,NaT,NaN,30.0,6653.64,675.0,0.0,0.10,7328.64,244.288000,30.54,7328.64,5228.64,200.0,600.0,1000.0,300.0,2100.0,200.0,0.0,0.0,500.0,100.0,800.0,8128.64,0,0,0.0,0.0,0.0,0.0,0.0,100.0,100.0,2026-01-01,8028.64,January,11
3,1004.0,4.0,Mariam Elsayed,Logistics Officer,Logistics,2022-07-24,1976-12-22,49.0,NaT,NaN,30.0,17071.77,0.0,0.0,0.00,17071.77,569.059000,71.13,17071.77,14871.77,150.0,750.0,1000.0,300.0,2200.0,300.0,150.0,100.0,0.0,0.0,550.0,17621.77,0,0,0.0,0.0,0.0,0.0,0.0,100.0,100.0,2026-01-01,17521.77,January,7
4,1005.0,5.0,Mostafa Mansour,Maintenance Engineer,Maintenance,2025-04-13,1997-01-30,29.0,NaT,NaN,30.0,7038.15,0.0,240.0,0.03,7278.15,242.605000,30.32,7278.15,6028.15,250.0,500.0,0.0,500.0,1250.0,0.0,400.0,0.0,1000.0,100.0,1500.0,8778.15,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-01-01,8778.15,January,4

#### Totals

In [20]:
total_salaries = round(df['Net Salary'].sum())
total_employess = df['Employee ID'].nunique()
total_earning = df['Total Variable Pay'].sum()
total_deductions = round(df['Total Penalties'].sum())

In [21]:
totalsalaries = df.groupby('Department')['Gross Salary'].sum().sort_values(ascending=False).reset_index()
totalsalaries

                Department  Gross Salary
0          Human Resources    3692413.63
1                    Sales    2545973.59
2           Administration    2506189.43
3   Information Technology    2383981.93
4                  Quality    2252682.88
5              Maintenance    2057156.42
6              Procurement    1949184.40
7                Logistics    1850743.18
8               Production    1707423.69
9                  Finance    1595955.73
10        Customer Service    1563156.06
11             Warehousing    1371590.03

In [22]:
px.bar(data_frame= totalsalaries , x='Department' , y='Gross Salary',text_auto=True)

In [24]:
count_employees_per_dep = (
    df.groupby('Department')
    .agg(
            Employees_Count = ('Employee ID','nunique'),
            Total_Salaries = ('Gross Salary','sum')
    )
    .sort_values(by='Total_Salaries' , ascending=False)
    .reset_index()
)
count_employees_per_dep

                Department  Employees_Count  Total_Salaries
0          Human Resources               34      3692413.63
1                    Sales               27      2545973.59
2           Administration               26      2506189.43
3   Information Technology               25      2383981.93
4                  Quality               22      2252682.88
5              Maintenance               22      2057156.42
6              Procurement               18      1949184.40
7                Logistics               15      1850743.18
8               Production               16      1707423.69
9                  Finance               19      1595955.73
10        Customer Service               14      1563156.06
11             Warehousing               16      1371590.03

In [25]:
px.bar(data_frame= count_employees_per_dep , x='Department' , y='Employees_Count',text_auto=True)

In [26]:
px.bar(data_frame= count_employees_per_dep , x='Department' , y=['Employees_Count','Total_Salaries'],text_auto=True,barmode='group')

In [27]:
total_employees_per_title = df.groupby('Job Title')['Employee ID'].nunique().sort_values(ascending=False).reset_index()
total_employees_per_title

                       Job Title  Employee ID
0                 Branch Manager           26
1                   Data Analyst           25
2           Maintenance Engineer           22
3                Quality Officer           22
4                     Accountant           19
5            Procurement Officer           18
6                  HR Specialist           17
7   Personnel Affairs Specialist           17
8          Production Technician           16
9           Warehouse Supervisor           16
10             Logistics Officer           15
11   Customer Service Specialist           14
12                 Sales Officer           14
13          Sales Representative           13

In [28]:
total_salaries_per_title = (df.groupby(['Job Title'])
.agg(
    Total_Salaries = ('Gross Salary','sum'),
    Total_Employees = ('Employee ID','nunique')
    )
.sort_values(ascending=False , by =['Total_Salaries'])
.reset_index()
)
total_salaries_per_title

                       Job Title  Total_Salaries  Total_Employees
0                 Branch Manager      2506189.43               26
1                   Data Analyst      2383981.93               25
2                Quality Officer      2252682.88               22
3           Maintenance Engineer      2057156.42               22
4            Procurement Officer      1949184.40               18
5   Personnel Affairs Specialist      1851732.81               17
6              Logistics Officer      1850743.18               15
7                  HR Specialist      1840680.82               17
8          Production Technician      1707423.69               16
9                     Accountant      1595955.73               19
10   Customer Service Specialist      1563156.06               14
11                 Sales Officer      1400541.85               14
12          Warehouse Supervisor      1371590.03               16
13          Sales Representative      1145431.74               13

In [31]:
total_salaries_per_month = df.groupby(['Salaries Month','Month_num'])['Gross Salary'].sum().reset_index().sort_values(by='Month_num')
total_salaries_per_month

  Salaries Month  Month_num  Gross Salary
3        January          1    2559077.20
2       February          2    2661678.33
6          March          3    2671075.54
0          April          4    2745639.55
7            May          5    2788612.55
5           June          6    2881505.14
4           July          7    2985848.16
1         August          8    3090468.68
8      September          9    3092545.82

In [32]:
px.pie(data_frame=total_salaries_per_month,names='Salaries Month',values='Gross Salary',title= 'Months Salaries')

In [33]:
px.line(data_frame=total_salaries_per_month,x='Salaries Month',y='Gross Salary')

In [34]:
tota_new_hires = df[df['Hire Date'].dt.year == 2026]['Employee ID'].nunique()
tota_new_hires

54

In [35]:
total_hires = (
    df[df['Hire Date'].dt.year == 2026]
    .groupby(df['Hire Date'].dt.month_name())
    ['Employee ID']
    .nunique()
    .reset_index()
)
total_hires

   Hire Date  Employee ID
0      April            8
1     August            9
2   February            7
3       July            8
4       June            7
5      March            4
6        May            7
7  September            4

In [36]:
px.line(data_frame=total_hires , x='Hire Date' , y='Employee ID',text='Employee ID',title ='New Hires').update_traces(textposition = 'top center')

In [37]:
total_new_leaves = df[df['Hire Date'].dt.year == 2026]['Termination Reason'].count()
total_new_leaves

np.int64(3)

In [38]:
total_leaves = df.groupby('Department')['Termination Reason'].count().sort_values(ascending=False).reset_index()
total_leaves

                Department  Termination Reason
0         Customer Service                   3
1               Production                   3
2                  Quality                   3
3           Administration                   2
4   Information Technology                   2
5              Procurement                   2
6                    Sales                   2
7                  Finance                   1
8              Maintenance                   1
9              Warehousing                   1
10         Human Resources                   0
11               Logistics                   0

In [39]:
total_leaves_titles = (
    df.groupby('Job Title')
    .agg(
            Total_Leaves= ('Termination Reason','count'),
            Total_Employees = ('Employee ID' , 'nunique')
    )
    .reset_index())
total_leaves_titles

                       Job Title  Total_Leaves  Total_Employees
0                     Accountant             1               19
1                 Branch Manager             2               26
2    Customer Service Specialist             3               14
3                   Data Analyst             2               25
4                  HR Specialist             0               17
5              Logistics Officer             0               15
6           Maintenance Engineer             1               22
7   Personnel Affairs Specialist             0               17
8            Procurement Officer             2               18
9          Production Technician             3               16
10               Quality Officer             3               22
11                 Sales Officer             2               14
12          Sales Representative             0               13
13          Warehouse Supervisor             1               16

In [40]:
total_leaves_titles['Turnover_Ratio'] = (
    total_leaves_titles['Total_Leaves']
    .div(total_leaves_titles['Total_Employees'])
    .mul(100)
    .fillna(0)
    .round()
)
total_leaves_titles

,Job Title,Total_Leaves,Total_Employees,Turnover_Ratio
0,Accountant,1,19,5.0
1,Branch Manager,2,26,8.0
2,Customer Service Specialist,3,14,21.0
3,Data Analyst,2,25,8.0
4,HR Specialist,0,17,0.0
5,Logistics Officer,0,15,0.0
6,Maintenance Engineer,1,22,5.0
7,Personnel Affairs Specialist,0,17,0.0
8,Procurement Officer,2,18,11.0
9,Production Technician,3,16,19.0
10,Quality Officer,3,22,14.0
11,Sales Officer,2,14,14.0
12,Sales Representative,0,13,0.0
13,Warehouse Supervisor,1,16,6.0

In [41]:
total_leaves_titles['Turnover_Ratio'] = (
    total_leaves_titles['Turnover_Ratio'].map('{:.1f}%'.format)
)
total_leaves_titles

                       Job Title  Total_Leaves  Total_Employees Turnover_Ratio
0                     Accountant             1               19           5.0%
1                 Branch Manager             2               26           8.0%
2    Customer Service Specialist             3               14          21.0%
3                   Data Analyst             2               25           8.0%
4                  HR Specialist             0               17           0.0%
5              Logistics Officer             0               15           0.0%
6           Maintenance Engineer             1               22           5.0%
7   Personnel Affairs Specialist             0               17           0.0%
8            Procurement Officer             2               18          11.0%
9          Production Technician             3               16          19.0%
10               Quality Officer             3               22          14.0%
11                 Sales Officer             2               14          14.0%
12          Sales Representative             0               13           0.0%
13          Warehouse Supervisor             1               16           6.0%

In [42]:
total_leaves_per_dep = df.groupby('Department').agg(Total_Leaves= ('Termination Reason','count'),
                         Total_Employess = ('Employee ID' , 'nunique')
                         
                    ).reset_index()
total_leaves_per_dep

                Department  Total_Leaves  Total_Employess
0           Administration             2               26
1         Customer Service             3               14
2                  Finance             1               19
3          Human Resources             0               34
4   Information Technology             2               25
5                Logistics             0               15
6              Maintenance             1               22
7              Procurement             2               18
8               Production             3               16
9                  Quality             3               22
10                   Sales             2               27
11             Warehousing             1               16

In [43]:
px.bar(data_frame=total_leaves_per_dep , x='Department' , y=['Total_Employess','Total_Leaves'], text_auto= True , title='Total Employees and Leaves per Department',barmode='group')

In [44]:
reasons_of_termination = df.groupby('Termination Reason')['Employee ID'].count().reset_index()
reasons_of_termination

             Termination Reason  Employee ID
0   Absence and Job Abandonment            5
1           Contract Expiration            3
2  Moved to Another Opportunity            2
3              Personal Reasons            4
4                   Resignation            6

In [45]:
px.pie(data_frame=reasons_of_termination,names='Termination Reason' , values='Employee ID',title='Termination Reasons')

In [46]:
total_leaves_per_Month = df.groupby(['Month_num','Salaries Month'])['Termination Reason'].count().reset_index().sort_values(by='Month_num')
total_leaves_per_Month

   Month_num Salaries Month  Termination Reason
0          1        January                   0
1          2       February                   3
2          3          March                   2
3          4          April                   2
4          5            May                   2
5          6           June                   2
6          7           July                   2
7          8         August                   5
8          9      September                   2

In [47]:
px.line(data_frame=total_leaves_per_Month,
        x='Salaries Month',
        y='Termination Reason',
        title = 'Termination per Months',
        labels=
            {
                'Termination Reason':'Count',
                'Salaries Month' : 'Months'
            },
        text= 'Termination Reason'
        ).update_traces(textposition = 'top center')

##### Cumulative Increasement

In [48]:
# Calculate the increasement for each employee

df=df.sort_values(['Employee ID' , 'Month_num'])
df['Monthly Increase'] = (
    df.groupby(['Employee ID'])['Additional Raise During 2026'].diff()
    .fillna(df['Additional Raise During 2026'])
)

df

,Employee ID,Serial Number,Employee Name,Job Title,Department,Hire Date,Date of Birth,Age,Last Working Day (If Terminated),Termination Reason,Working Days,2025 Salary,January 2026 Raise,Additional Raise During 2026,January 2026 Raise Rate,Gross Salary,Daily Wage,Hourly Wage,Monthly Salary,Basic Salary,Clothing Allowance,Transportation Allowance,Housing Allowance,Meal Allowance,Total Allowances,Variable Allowances,Business Trip Allowance,Additional Allowance,Bonuses and Incentives,Other Earnings,Total Variable Pay,Total Salary,Absence Days,Absence Penalty (Days),Absence Deduction Amount,Statutory Penalty (Days),Statutory Penalty Amount,Administrative Penalty (Days),Administrative Penalty Amount,Other Monetary Penalties,Total Penalties,Month,Net Salary,Salaries Month,Months,Month_num,Monthly Increase
0,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaT,NaN,30.0,7809.12,810.0,0.0,0.10,8619.12,287.304000,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,0.0,0.0,100.0,0.0,0.0,100.0,8719.12,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,2026-01-01,8719.120000,January,8,1,0.0
200,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaT,NaN,30.0,7809.12,810.0,0.0,0.10,8619.12,287.304000,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,0.0,150.0,100.0,0.0,0.0,250.0,8869.12,0,0,0.000000,0.0,0.0,0.0,0.0,150.0,150.000000,2026-02-01,8719.120000,February,8,2,0.0
407,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaT,NaN,30.0,7809.12,810.0,0.0,0.10,8619.12,287.304000,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,100.0,0.0,100.0,750.0,50.0,1000.0,9619.12,0,0,0.000000,0.0,0.0,0.0,0.0,150.0,150.000000,2026-03-01,9469.120000,March,8,3,0.0
615,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaT,NaN,30.0,7809.12,810.0,0.0,0.10,8619.12,287.304000,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,100.0,400.0,250.0,0.0,200.0,950.0,9569.12,0,0,0.000000,0.0,0.0,0.0,0.0,150.0,150.000000,2026-04-01,9419.120000,April,8,4,0.0
829,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaT,NaN,30.0,7809.12,810.0,0.0,0.10,8619.12,287.304000,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,0.0,0.0,0.0,300.0,0.0,300.0,8919.12,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,2026-05-01,8919.120000,May,8,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,1250.0,232.0,Aya Morad,Quality Officer,Quality,2026-08-30,1976-07-29,50.0,NaT,NaN,30.0,16769.03,0.0,0.0,0.00,16769.03,558.967667,69.87,16769.03,15769.03,200.0,500.0,0.0,300.0,1000.0,0.0,0.0,0.0,1000.0,50.0,1050.0,17819.03,1,1,1117.935333,0.0,0.0,0.0,0.0,150.0,1267.935333,2026-09-01,16551.094667,September,8,9,0.0
1971,1251.0,233.0,Heba Adel,Maintenance Engineer,Maintenance,2026-09-23,1988-01-04,38.0,NaT,NaN,8.0,13272.31,750.0,450.0,0.09,14472.31,482.410333,60.30,14472.31,12322.31,300.0,500.0,750.0,600.0,2150.0,100.0,0.0,250.0,1000.0,50.0,1400.0,15872.31,4,4,3859.282667,0.0,0.0,0.0,0.0,0.0,3859.282667,2026-09-01,12013.027333,September,9,9,450.0
1733,1252.0,234.0,Iman Elsayed,HR Specialist,Human Resources,2026-09-29,1994-12-14,31.0,NaT,NaN,2.0,8645.41,800.0,0.0,0.09,9445.41,314.847000,39.36,9445.41,6795.41,150.0,600.0,1500.0,400.0,2650.0,200.0,0.0,0.0,500.0,100.0,800.0,10245.41,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,2026-09-01,10245.410000,September,9,9,0.0
1973,1253.0,235.0,Ahmed Mahmoud,Warehouse Supervisor,Warehousing,2026-09-02,1977-12-20,48.0,NaT,NaN,29.0,9691.43,787.5,0.0,0.08,10478.93,349.297667,43.66,10478.93,8678.93,150.0,600.0,750.0,300.0,1800.0,200.0,0.0,150.0,0.0,0.0,350.0,10828.93,0,0,0.000000,0.0,0.0,0.0,0.0,150.0,150.000000,2026-09-01,10678.930000,September,9,9,0.0
1974,1254.0,236.0,Iman Samir,Quality Officer,Quality,2026-09-30,1984-01-27,42.0,NaT,NaN,1.0,15066.10,1680.0,630.0,0.15,17376.10,579.203333,72.40,17376.10,16426.10,150.0,400.0,0.0,400.0,950.0,500.0,0.0,250.0,500.0,0.0,1250.0,18626.10,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,2026-09-01,18626.100000,September,9,9,630.0

In [49]:
total_increase_per_month = (
    df.groupby(['Month_num', 'Salaries Month'])['Monthly Increase'].sum()
    .reset_index()
    .sort_values('Month_num')
)

total_increase_per_month

   Month_num Salaries Month  Monthly Increase
0          1        January           72690.0
1          2       February            4657.5
2          3          March             712.5
3          4          April            3535.0
4          5            May            2525.0
5          6           June            2722.5
6          7           July            3752.5
7          8         August            2750.0
8          9      September            1080.0

In [50]:
px.bar(data_frame=total_increase_per_month,
    x='Salaries Month',
    y='Monthly Increase',
    title = 'Raises per Months',
    labels = {

        'Salaries Month' : 'Months',
        'Monthly Increase': 'Total Increasement'
   
         },
    text_auto= True)

In [51]:
px.line(
    data_frame=total_increase_per_month,
    x='Salaries Month',
    y='Monthly Increase',
    title = 'Raises per Months',
    labels = {

        'Salaries Month' : 'Months',
        'Monthly Increase': 'Total Increasement'
   
         },
    text= 'Monthly Increase'
).update_traces(textposition = 'top center')

#### Earning Analysis

##### Totals Earnings

In [ ]:
total_bonus = df['Bonuses and Incentives'].sum()
total_additional_allowance = df['Additional Allowance'].sum()
total_other_earnings = df['Other Earnings'].sum()
total_variable_allowance = df['Variable Allowances'].sum()
Business_Trip_Allowance = df['Business Trip Allowance'].sum()
df

In [52]:


allowance_col=[
'Bonuses and Incentives',
'Additional Allowance',
'Other Earnings',
'Variable Allowances',
'Business Trip Allowance'
]

allowance_dataframe_summary = (df[allowance_col].sum().reset_index())
allowance_dataframe_summary.columns = ['Earning type' , 'Total Amount']
allowance_dataframe_summary

px.bar(
    data_frame=allowance_dataframe_summary,
    x='Earning type',
    y='Total Amount',
    text_auto=True,
    title = 'Total Earning Amount by Type'
)

In [53]:
total_bonus_per_department = df.groupby('Department')['Bonuses and Incentives'].sum().reset_index()
total_bonus_per_department

                Department  Bonuses and Incentives
0           Administration                 73750.0
1         Customer Service                 36550.0
2                  Finance                 38500.0
3          Human Resources                 95500.0
4   Information Technology                 77550.0
5                Logistics                 51500.0
6              Maintenance                 64150.0
7              Procurement                 52550.0
8               Production                 38950.0
9                  Quality                 61600.0
10                   Sales                 82950.0
11             Warehousing                 39650.0

In [54]:
total_trip_emp = df[df['Business Trip Allowance']>0].groupby('Department')['Employee ID'].nunique().reset_index()
total_trip_emp

                Department  Employee ID
0           Administration           25
1         Customer Service           13
2                  Finance           18
3          Human Resources           33
4   Information Technology           25
5                Logistics           14
6              Maintenance           21
7              Procurement           17
8               Production           15
9                  Quality           20
10                   Sales           27
11             Warehousing           15

In [59]:
px.pie(
    data_frame=total_trip_emp,
    names = 'Department',
    values= 'Employee ID',
    title ='No.Trips Emplyees',
    hole = .45
).update_traces(textinfo = 'label+value+percent').update_layout(showlegend =False)

In [60]:
px.bar(data_frame=total_bonus_per_department,x='Department',y='Bonuses and Incentives',title='Bonus per Department',text_auto=True)

In [61]:
total_earnings_per_department = df.groupby('Department')['Total Variable Pay'].sum().reset_index()
total_earnings_per_department

                Department  Total Variable Pay
0           Administration            176050.0
1         Customer Service            100400.0
2                  Finance            108350.0
3          Human Resources            224200.0
4   Information Technology            184500.0
5                Logistics            122700.0
6              Maintenance            153000.0
7              Procurement            124400.0
8               Production             95850.0
9                  Quality            150350.0
10                   Sales            190750.0
11             Warehousing             95300.0

In [62]:
total_bonus_per_month = df.groupby(['Salaries Month','Month_num'])['Bonuses and Incentives'].sum().reset_index().sort_values(by='Month_num')
total_bonus_per_month

  Salaries Month  Month_num  Bonuses and Incentives
3        January          1                 66800.0
2       February          2                 82100.0
6          March          3                 73750.0
0          April          4                 70900.0
7            May          5                 85050.0
5           June          6                 80900.0
4           July          7                 81650.0
1         August          8                 84600.0
8      September          9                 87450.0

In [63]:
px.line(data_frame=total_bonus_per_month,x='Salaries Month',y='Bonuses and Incentives',title='Bonus per Months',text='Bonuses and Incentives',labels={'Salaries Month':'Months'}).update_traces(textposition = 'top center')

In [64]:
total_bonus_emp_per_month = df.groupby(['Salaries Month','Month_num']).agg(
    TotalBonus = ('Bonuses and Incentives', 'sum'),
    TotalEmployees = ('Employee ID' , 'nunique')
    ).reset_index().sort_values(by='Month_num')
total_bonus_emp_per_month

  Salaries Month  Month_num  TotalBonus  TotalEmployees
3        January          1     66800.0             200
2       February          2     82100.0             207
6          March          3     73750.0             208
0          April          4     70900.0             214
7            May          5     85050.0             219
5           June          6     80900.0             224
4           July          7     81650.0             230
1         August          8     84600.0             237
8      September          9     87450.0             236

In [65]:
px.bar(
    data_frame=total_bonus_emp_per_month,
    x='Salaries Month',
    y=['TotalBonus','TotalEmployees'],
    title='Bonus per Months',
    labels={'Salaries Month':'Months'},
    barmode='group',
    text_auto= True
    )

#### Deduction

##### Totals Deductions

In [ ]:
total_absence_value = round(df['Absence Deduction Amount'].sum())
total_statutory_value = round(df['Statutory Penalty Amount'].sum())
total_administrative_penalty_value = round(df['Administrative Penalty Amount'].sum())

In [ ]:
filtered_ded_data = df[df['Total Penalties']>0]
filtered_ded_data

In [ ]:
total_pen_month = filtered_ded_data.groupby(['Salaries Month' , 'Month_num']).agg(
    total_employees = ('Employee ID','nunique'),
    total_val = ('Total Penalties' , 'sum')
).reset_index().sort_values(by='Month_num').round()
total_pen_dep

In [97]:
px.line(
    data_frame=total_pen_dep,
    x='Salaries Month',
    y='total_val',
    text='total_val',
    title= 'Total Penalties per Month'
).update_traces(textposition = 'top center')

In [ ]:
absence_ratio = (df['Absence Days'].sum()/ df['Employee ID'].nunique())
absence_ratio

In [ ]:
filtered_absence_data = df[df['Absence Days']>0]
filtered_absence_data

In [82]:
total_employess_absence = (
                            filtered_absence_data.groupby('Department')
                            .agg(
                                Total_Employees=('Employee ID','nunique'),
                                Total_Absence_Days=('Absence Days','sum'),
                                Total_Absence_Penlty = ('Absence Penalty (Days)' , 'sum'))
                            .reset_index()
                           
)
total_employess_absence

,Department,Total_Employees,Total_Absence_Days,Total_Absence_Penlty
0,Administration,9,17,17
1,Customer Service,6,11,11
2,Finance,5,10,8
3,Human Resources,9,45,25
4,Information Technology,13,46,34
5,Logistics,8,28,13
6,Maintenance,9,27,27
7,Procurement,6,20,15
8,Production,8,16,15
9,Quality,6,6,6
10,Sales,8,22,20
11,Warehousing,6,9,9

In [81]:
px.bar(data_frame=total_employess_absence,x='Department', y=['Total_Employees','Total_Absence_Days','Total_Absence_Penlty'] , title= 'Total Absence Employees per Department' , text_auto = True, barmode='group')

In [83]:
total_employess_disp_pnlties = (
                            df[df['Statutory Penalty (Days)']>0].groupby('Department')
                            .agg(
                                Total_Employees=('Employee ID','nunique'),
                                Total_Days=('Statutory Penalty (Days)','sum'))
                            .reset_index()
                           
)
total_employess_disp_pnlties

                Department  Total_Employees  Total_Days
0           Administration                5        4.50
1         Customer Service                5        5.50
2                  Finance                2        3.75
3          Human Resources               10       15.25
4   Information Technology                7        6.75
5                Logistics                3        5.25
6              Maintenance                6        6.75
7              Procurement                7        8.25
8               Production                4        2.75
9                  Quality                4        5.75
10                   Sales                6        4.75
11             Warehousing                3        0.75

In [84]:
px.bar(data_frame=total_employess_disp_pnlties,x='Department', y=['Total_Employees','Total_Days'] , title= 'Total Statutory Penalty per Department' , text_auto = True, barmode='group')

In [85]:
total_employess_admin_pnlties = (
                            df[df['Administrative Penalty (Days)']>0].groupby('Department')
                            .agg(
                                Total_Employees=('Employee ID','nunique'),
                                Total_Days=('Administrative Penalty (Days)','sum'))
                            .reset_index()
                           
)
total_employess_admin_pnlties

                Department  Total_Employees  Total_Days
0           Administration               13       28.75
1         Customer Service                4        6.50
2                  Finance                6       10.50
3          Human Resources                9       30.50
4   Information Technology               13       24.00
5                Logistics                9       17.50
6              Maintenance                8       15.50
7              Procurement                5       16.50
8               Production                5        8.50
9                  Quality                4        9.00
10                   Sales               10       13.00
11             Warehousing                4        4.00

In [86]:
px.bar(data_frame=total_employess_admin_pnlties,x='Department', y=['Total_Employees','Total_Days'] , title= 'Total Administrative Penalty per Department' , text_auto = True, barmode='group')

In [98]:
total_employess_admin_pnlties = (
                            df[df['Administrative Penalty (Days)']>0]['Employee ID'].nunique())

total_employess_admin_pnlties

90

In [99]:
df = df.sort_values(['Salaries Month','Employee ID'])
df

,Employee ID,Serial Number,Employee Name,Job Title,Department,Hire Date,Date of Birth,Age,Last Working Day (If Terminated),Termination Reason,Working Days,2025 Salary,January 2026 Raise,Additional Raise During 2026,January 2026 Raise Rate,Gross Salary,Daily Wage,Hourly Wage,Monthly Salary,Basic Salary,Clothing Allowance,Transportation Allowance,Housing Allowance,Meal Allowance,Total Allowances,Variable Allowances,Business Trip Allowance,Additional Allowance,Bonuses and Incentives,Other Earnings,Total Variable Pay,Total Salary,Absence Days,Absence Penalty (Days),Absence Deduction Amount,Statutory Penalty (Days),Statutory Penalty Amount,Administrative Penalty (Days),Administrative Penalty Amount,Other Monetary Penalties,Total Penalties,Month,Net Salary,Salaries Month,Months,Month_num,Monthly Increase
615,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaT,NaN,30.0,7809.12,810.0,0.0,0.10,8619.12,287.304000,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,100.0,400.0,250.0,0.0,200.0,950.0,9569.12,0,0,0.000000,0.0,0.0,0.0,0.0,150.0,150.000000,2026-04-01,9419.120000,April,8,4,0.0
616,1002.0,2.0,Mohamed Mohamed,Quality Officer,Quality,2025-02-25,1979-10-23,46.0,NaT,NaN,30.0,6642.09,775.0,232.5,0.15,7649.59,254.986333,31.87,7649.59,5999.59,150.0,400.0,500.0,600.0,1650.0,200.0,250.0,400.0,300.0,200.0,1350.0,8999.59,0,0,0.000000,0.0,0.0,0.0,0.0,150.0,150.000000,2026-04-01,8849.590000,April,2,4,0.0
617,1003.0,3.0,Heba Adel,Sales Representative,Sales,2023-11-01,1990-02-24,36.0,NaT,NaN,30.0,6653.64,675.0,0.0,0.10,7328.64,244.288000,30.54,7328.64,5228.64,200.0,600.0,1000.0,300.0,2100.0,200.0,0.0,0.0,0.0,0.0,200.0,7528.64,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,2026-04-01,7528.640000,April,11,4,0.0
618,1004.0,4.0,Mariam Elsayed,Logistics Officer,Logistics,2022-07-24,1976-12-22,49.0,NaT,NaN,30.0,17071.77,0.0,0.0,0.00,17071.77,569.059000,71.13,17071.77,14871.77,150.0,750.0,1000.0,300.0,2200.0,500.0,150.0,0.0,0.0,0.0,650.0,17721.77,0,0,0.000000,0.0,0.0,0.0,0.0,150.0,150.000000,2026-04-01,17571.770000,April,7,4,0.0
619,1005.0,5.0,Mostafa Mansour,Maintenance Engineer,Maintenance,2025-04-13,1997-01-30,29.0,NaT,NaN,30.0,7038.15,0.0,240.0,0.03,7278.15,242.605000,30.32,7278.15,6028.15,250.0,500.0,0.0,500.0,1250.0,0.0,0.0,100.0,0.0,0.0,100.0,7378.15,0,0,0.000000,0.0,0.0,0.0,0.0,100.0,100.000000,2026-04-01,7278.150000,April,4,4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,1250.0,232.0,Aya Morad,Quality Officer,Quality,2026-08-30,1976-07-29,50.0,NaT,NaN,30.0,16769.03,0.0,0.0,0.00,16769.03,558.967667,69.87,16769.03,15769.03,200.0,500.0,0.0,300.0,1000.0,0.0,0.0,0.0,1000.0,50.0,1050.0,17819.03,1,1,1117.935333,0.0,0.0,0.0,0.0,150.0,1267.935333,2026-09-01,16551.094667,September,8,9,0.0
1971,1251.0,233.0,Heba Adel,Maintenance Engineer,Maintenance,2026-09-23,1988-01-04,38.0,NaT,NaN,8.0,13272.31,750.0,450.0,0.09,14472.31,482.410333,60.30,14472.31,12322.31,300.0,500.0,750.0,600.0,2150.0,100.0,0.0,250.0,1000.0,50.0,1400.0,15872.31,4,4,3859.282667,0.0,0.0,0.0,0.0,0.0,3859.282667,2026-09-01,12013.027333,September,9,9,450.0
1733,1252.0,234.0,Iman Elsayed,HR Specialist,Human Resources,2026-09-29,1994-12-14,31.0,NaT,NaN,2.0,8645.41,800.0,0.0,0.09,9445.41,314.847000,39.36,9445.41,6795.41,150.0,600.0,1500.0,400.0,2650.0,200.0,0.0,0.0,500.0,100.0,800.0,10245.41,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,2026-09-01,10245.410000,September,9,9,0.0
1973,1253.0,235.0,Ahmed Mahmoud,Warehouse Supervisor,Warehousing,2026-09-02,1977-12-20,48.0,NaT,NaN,29.0,9691.43,787.5,0.0,0.08,10478.93,349.297667,43.66,10478.93,8678.93,150.0,600.0,750.0,300.0,1800.0,200.0,0.0,150.0,0.0,0.0,350.0,10828.93,0,0,0.000000,0.0,0.0,0.0,0.0,150.0,150.000000,2026-09-01,10678.930000,September,9,9,0.0
1974,1254.0,236.0,Iman Samir,Quality Officer,Quality,2026-09-30,1984-01-27,42.0,NaT,NaN,1.0,15066.10,1680.0,630.0,0.15,17376.10,579.203333,72.40,17376.10,16426.10,150.0,400.0,0.0,400.0,950.0,500.0,0.0,250.0,500.0,0.0,1250.0,18626.10,0,0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,2026-09-01,18626.100000,September,9,9,630.0

In [100]:
pd.DataFrame.to_parquet(df,"Cleaned data.parquet")