In [4]:
import pandas as pd
import numpy as np
import plotly.express as px
import openpyxl as op

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
df = pd.read_excel(r'/Users/menna/Python/EDA/Final Project/Dataset/payroll_sample.xlsx')
df

,Employee ID,Serial Number,Employee Name,Job Title,Department,Hire Date,Date of Birth,Age,Last Working Day (If Terminated),Termination Reason,Working Days,2025 Salary,January 2026 Raise,Additional Raise During 2026,January 2026 Raise Rate,Gross Salary,Daily Wage,Hourly Wage,Monthly Salary,Basic Salary,Clothing Allowance,Transportation Allowance,Housing Allowance,Meal Allowance,Total Allowances,Variable Allowances,Business Trip Allowance,Additional Allowance,Bonuses and Incentives,Other Earnings,Total Variable Pay,Total Salary,Absence Days,Absence Penalty (Days),Absence Deduction Amount,Statutory Penalty (Days),Statutory Penalty Amount,Administrative Penalty (Days),Administrative Penalty Amount,Other Monetary Penalties,Total Penalties,Empty Field 1,Month,Net Salary,Empty Field 2
0,1001.0,1.0,Khaled Mostafa,Accountant,Finance,2024-08-02,1974-08-07,51.0,NaN,NaN,30.0,6750.0,810.0,0.0,0.12,8619.12,287.30,35.91,8619.12,5769.12,300.0,750.0,1500.0,300.0,2850.0,0.0,0.0,100.0,0.0,0.0,100.0,8719.12,0,0,0,0.0,0,0.0,0,0.0,0,NaN,01/2026,7557.22,NaN
1,1002.0,2.0,Mohamed Mohamed,Quality Officer,Quality,2025-02-25,1979-10-23,46.0,NaN,NaN,30.0,7750.0,775.0,232.5,0.10,7649.59,254.99,31.87,7649.59,5999.59,150.0,400.0,500.0,600.0,1650.0,500.0,250.0,150.0,0.0,0.0,900.0,8549.59,0,0,0,0.0,0,0.0,0,100.0,0,NaN,01/2026,7029.63,NaN
2,1003.0,3.0,Heba Adel,Sales Representative,Sales,2023-11-01,1990-02-24,35.0,NaN,NaN,30.0,6750.0,675.0,0.0,0.10,7328.64,244.29,30.54,7328.64,5228.64,200.0,600.0,1000.0,300.0,2100.0,200.0,0.0,0.0,500.0,100.0,800.0,8128.64,0,0,0,0.0,0,0.0,0,100.0,0,NaN,01/2026,7778.64,NaN
3,1004.0,4.0,Mariam Elsayed,Logistics Officer,Logistics,2022-07-24,1976-12-22,49.0,NaN,NaN,30.0,20250.0,0.0,0.0,0.00,17071.77,569.06,71.13,17071.77,14871.77,150.0,750.0,1000.0,300.0,2200.0,300.0,150.0,100.0,0.0,0.0,550.0,17621.77,0,0,0,0.0,0,0.0,0,100.0,0,NaN,01/2026,17521.77,NaN
4,1005.0,5.0,Mostafa Mansour,Maintenance Engineer,Maintenance,2025-04-13,1997-01-30,29.0,NaN,NaN,30.0,8000.0,0.0,240.0,0.00,7278.15,242.60,30.32,7278.15,6028.15,250.0,500.0,0.0,500.0,1250.0,0.0,400.0,0.0,1000.0,100.0,1500.0,8778.15,0,0,0,0.0,0,0.0,0,0.0,0,NaN,01/2026,7750.35,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1971,1251.0,233.0,Heba Adel,Maintenance Engineer,Maintenance,2026-09-23,1988-01-04,38.0,NaN,NaN,8.0,15000.0,750.0,450.0,0.05,14472.31,482.41,60.30,14472.31,12322.31,300.0,500.0,750.0,600.0,2150.0,100.0,0.0,250.0,1000.0,50.0,1400.0,5259.28,4,4,6666٫666667,0.0,0,0.0,0,0.0,6666٫666667,NaN,09/2026,5259.28,NaN
1972,1223.0,216.0,Mostafa Fouad,Personnel Affairs Specialist,Human Resources,2026-05-27,2000-12-23,25.0,NaN,NaN,4.0,8000.0,560.0,400.0,0.07,7054.13,235.14,29.39,7054.13,5954.13,300.0,400.0,0.0,400.0,1100.0,300.0,0.0,100.0,500.0,100.0,1000.0,1940.55,0,0,0,1.0,4000,0.0,0,100.0,4000,NaN,05/2026,1035.13,NaN
1973,1253.0,235.0,Ahmed Mahmoud,Warehouse Supervisor,Warehousing,2026-09-02,1977-12-20,48.0,NaN,NaN,29.0,11250.0,787.5,0.0,0.07,10478.93,349.30,43.66,10478.93,8678.93,150.0,600.0,750.0,300.0,1800.0,200.0,0.0,150.0,0.0,0.0,350.0,10479.63,0,0,0,0.0,0,0.0,0,150.0,0,NaN,09/2026,9980.33,NaN
1974,1254.0,236.0,Iman Samir,Quality Officer,Quality,2026-09-30,1984-01-27,42.0,NaN,NaN,1.0,21000.0,1680.0,630.0,0.08,17376.10,579.20,72.40,17376.10,16426.10,150.0,400.0,0.0,400.0,950.0,500.0,0.0,250.0,500.0,0.0,1250.0,1829.20,0,0,0,0.0,0,0.0,0,0.0,0,NaN,09/2026,1729.20,NaN
1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.0,0,0.0,0,NaN,0,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1976 entries, 0 to 1975
Data columns (total 45 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Employee ID                       1975 non-null   float64
 1   Serial Number                     1975 non-null   float64
 2   Employee Name                     1975 non-null   str
 3   Job Title                         1975 non-null   str
 4   Department                        1975 non-null   str
 5   Hire Date                         1975 non-null   str
 6   Date of Birth                     1975 non-null   str
 7   Age                               1975 non-null   float64
 8   Last Working Day (If Terminated)  20 non-null     str
 9   Termination Reason                20 non-null     str
 10  Working Days                      1975 non-null   float64
 11  2025 Salary                       1975 non-null   float64
 12  January 2026 Raise                1975 non-null   float64
 13  Additional Raise During 2026      1975 non-null   float64
 14  January 2026 Raise Rate           1975 non-null   float64
 15  Gross Salary                      1975 non-null   float64
 16  Daily Wage                        1975 non-null   float64
 17  Hourly Wage                       1975 non-null   float64
 18  Monthly Salary                    1975 non-null   float64
 19  Basic Salary                      1975 non-null   float64
 20  Clothing Allowance                1975 non-null   float64
 21  Transportation Allowance          1975 non-null   float64
 22  Housing Allowance                 1975 non-null   float64
 23  Meal Allowance                    1975 non-null   float64
 24  Total Allowances                  1975 non-null   float64
 25  Variable Allowances               1975 non-null   float64
 26  Business Trip Allowance           1975 non-null   float64
 27  Additional Allowance              1975 non-null   float64
 28  Bonuses and Incentives            1975 non-null   float64
 29  Other Earnings                    1975 non-null   float64
 30  Total Variable Pay                1975 non-null   float64
 31  Total Salary                      1975 non-null   float64
 32  Absence Days                      1976 non-null   int64
 33  Absence Penalty (Days)            1976 non-null   int64
 34  Absence Deduction Amount          1976 non-null   object
 35  Statutory Penalty (Days)          1976 non-null   float64
 36  Statutory Penalty Amount          1976 non-null   object
 37  Administrative Penalty (Days)     1976 non-null   float64
 38  Administrative Penalty Amount     1976 non-null   object
 39  Other Monetary Penalties          1975 non-null   float64
 40  Total Penalties                   1976 non-null   object
 41  Empty Field 1                     0 non-null      float64
 42  Month                             1975 non-null   str
 43  Net Salary                        1975 non-null   float64
 44  Empty Field 2                     0 non-null      float64
dtypes: float64(31), int64(2), object(4), str(8)
memory usage: 829.5+ KB

In [8]:
df.describe()

,Employee ID,Serial Number,Age,Working Days,2025 Salary,January 2026 Raise,Additional Raise During 2026,January 2026 Raise Rate,Gross Salary,Daily Wage,Hourly Wage,Monthly Salary,Basic Salary,Clothing Allowance,Transportation Allowance,Housing Allowance,Meal Allowance,Total Allowances,Variable Allowances,Business Trip Allowance,Additional Allowance,Bonuses and Incentives,Other Earnings,Total Variable Pay,Total Salary,Absence Days,Absence Penalty (Days),Statutory Penalty (Days),Administrative Penalty (Days),Other Monetary Penalties,Empty Field 1,Net Salary,Empty Field 2
count,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1975.000000,1976.000000,1976.000000,1976.000000,1976.000000,1975.000000,0.0,1975.000000,0.0
mean,1115.695190,110.578734,39.256203,29.396962,13877.974684,925.288608,373.029114,0.068192,12899.468846,429.982253,53.747610,12899.468846,10827.063782,232.278481,627.594937,775.063291,437.468354,2072.405063,154.886076,135.822785,153.974684,361.113924,68.050633,873.848101,13513.792754,0.130061,0.101215,0.035425,0.093244,48.860759,NaN,12653.967782,NaN
std,66.525481,63.977594,9.291638,3.552813,4641.182328,606.131610,425.930836,0.037732,3670.396696,122.346444,15.293269,3670.396696,3646.008867,54.390548,177.817564,505.671666,114.428543,550.490744,174.908211,152.284259,143.759584,372.675878,72.911637,468.329153,3936.412021,0.785816,0.570923,0.202072,0.504979,57.139410,NaN,3836.636386,NaN
min,1001.000000,1.000000,23.000000,1.000000,6500.000000,0.000000,0.000000,0.000000,6132.440000,204.410000,25.550000,6132.440000,4775.080000,150.000000,400.000000,0.000000,300.000000,850.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,673.720000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,NaN
25%,1059.000000,55.000000,31.000000,30.000000,10000.000000,560.000000,0.000000,0.050000,9628.050000,320.940000,40.120000,9628.050000,7730.510000,200.000000,500.000000,500.000000,300.000000,1700.000000,0.000000,0.000000,0.000000,0.000000,0.000000,500.000000,10319.005000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,9684.285000,NaN
50%,1115.000000,110.000000,39.000000,30.000000,13750.000000,875.000000,247.500000,0.070000,12728.200000,424.270000,53.030000,12728.200000,10628.200000,250.000000,600.000000,750.000000,400.000000,2100.000000,100.000000,150.000000,150.000000,300.000000,50.000000,850.000000,13571.950000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,12584.240000,NaN
75%,1172.000000,165.000000,47.000000,30.000000,17500.000000,1347.500000,662.500000,0.100000,15950.085000,531.670000,66.460000,15950.085000,13834.630000,300.000000,750.000000,1000.000000,500.000000,2500.000000,300.000000,250.000000,250.000000,750.000000,100.000000,1200.000000,16682.155000,0.000000,0.000000,0.000000,0.000000,100.000000,NaN,15522.970000,NaN
max,1254.000000,237.000000,56.000000,30.000000,22000.000000,2610.000000,1540.000000,0.120000,21388.400000,712.950000,89.120000,21388.400000,19390.980000,300.000000,900.000000,1500.000000,600.000000,3150.000000,500.000000,400.000000,400.000000,1000.000000,200.000000,2500.000000,23338.400000,15.000000,10.000000,3.000000,5.000000,200.000000,NaN,23238.400000,NaN

In [ ]:
df.isna().sum()

In [ ]:
df = df.dropna()
df.isna().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
df.describe(include= 'object')

In [ ]:
df['Hire Date'] = pd.to_datetime(df['Hire Date'])
df['Date of Birth'] = pd.to_datetime(df['Date of Birth'])
df['Last Working Day (If Terminated)'] = pd.to_datetime(df['Last Working Day (If Terminated)'])
df['Month'] = pd.to_datetime(df['Month'])
df.info()

In [ ]:
df.drop(columns=['Empty Field 1' , 'Empty Field 2'] , inplace=True)
df

In [ ]:
num_col =df.select_dtypes(include = 'number').columns.drop(['Employee ID', 'Serial Number'])
num_col

In [ ]:
for col in num_col:
    px.histogram(data_frame= df , x= col , title= col).show()
    px.box(data_frame= df , x=col , title=col).show()

### Feature Engineering

In [ ]:
df['2025 Salary'] = df['Gross Salary']-(df['January 2026 Raise']+df['Additional Raise During 2026'])
df['January 2026 Raise Rate'] = round((df['January 2026 Raise']+df['Additional Raise During 2026']) / df['2025 Salary'],2)
df

In [ ]:
df['Absence Deduction Amount']=(df['Absence Penalty (Days)']+df['Absence Days'])*df['Daily Wage']
df['Statutory Penalty Amount']=pd.to_numeric(df['Statutory Penalty (Days)'])*df['Daily Wage']
df['Administrative Penalty Amount']=df['Administrative Penalty (Days)']*df['Daily Wage']
df['Total Penalties'] = df['Absence Deduction Amount'] + df['Statutory Penalty Amount']+df['Administrative Penalty Amount']+df['Other Monetary Penalties']
df['Net Salary'] = df['Total Salary']-df['Total Penalties']

df

In [ ]:
df['Salaries Month'] = df['Month'].dt.month_name()
df['Salaries Month']

In [ ]:
df['Month_num'] = df['Month'].dt.month
df['Month_num']

### Data Analysis

In [ ]:
df.head()

#### Totals

In [ ]:
total_salaries = round(df['Net Salary'].sum())
total_employess = df['Employee ID'].nunique()
total_earning = df['Total Variable Pay'].sum()
total_deductions = round(df['Total Penalties'].sum())

In [ ]:
totalsalaries = df.groupby('Department')['Gross Salary'].sum().sort_values(ascending=False).reset_index()
totalsalaries

In [ ]:
px.bar(data_frame= totalsalaries , x='Department' , y='Gross Salary',text_auto=True)

In [ ]:
count_employees_per_dep = (
    df.groupby('Department')
    .agg(
            Employees_Count = ('Employee ID','nunique'),
            Total_Salaries = ('Gross Salary','sum')
    )
    .sort_values(by='Total_Salaries' , ascending=False)
    .reset_index()
)
count_employees_per_dep

In [ ]:
px.bar(data_frame= count_employees_per_dep , x='Department' , y='Employees_Count',text_auto=True)

In [ ]:
px.bar(data_frame= count_employees_per_dep , x='Department' , y=['Employees_Count','Total_Salaries'],text_auto=True,barmode='group')

In [ ]:
total_employees_per_title = df.groupby('Job Title')['Employee ID'].nunique().sort_values(ascending=False).reset_index()
total_employees_per_title

In [ ]:
total_salaries_per_title = (df.groupby('Job Title')
.agg(
    Total_Salaries = ('Gross Salary','sum'),
    Total_Employees = ('Employee ID','nunique')
    )
.sort_values(ascending=False , by =['Total_Salaries'])
.reset_index()
)
total_salaries_per_title

In [ ]:
total_salaries_per_month = df.groupby(['Salaries Month','Month_num'])['Gross Salary'].sum().reset_index().sort_values(by='Month_num')
total_salaries_per_month

In [ ]:
px.pie(data_frame=total_salaries_per_month,names='Salaries Month',values='Gross Salary',title= 'Months Salaries')

In [ ]:
px.line(data_frame=total_salaries_per_month,x='Salaries Month',y='Gross Salary')

In [ ]:
df['Months']=df['Hire Date'].dt.month
df['Months']

In [ ]:

total_hires = (
    df[df['Hire Date'].dt.year == 2026]
    .groupby(df['Hire Date'].dt.month_name())
    ['Employee ID']
    .nunique()
    .reset_index()
)
total_hires

In [ ]:
tota_new_hires = df[df['Hire Date'].dt.year == 2026]['Employee ID'].nunique()
tota_new_hires

In [ ]:
total_new_leaves = df[df['Hire Date'].dt.year == 2026]['Termination Reason'].count()
total_new_leaves

In [ ]:
px.line(data_frame=total_hires , x='Hire Date' , y='Employee ID',text='Employee ID',title ='New Hires').update_traces(textposition = 'top center')

In [ ]:
total_leaves = df.groupby('Department')['Termination Reason'].count().sort_values(ascending=False).reset_index()
total_leaves

In [ ]:
total_leaves_titles = (
    df.groupby('Job Title')
    .agg(
            Total_Leaves= ('Termination Reason','count'),
            Total_Employees = ('Employee ID' , 'nunique')
    )
    .reset_index())
total_leaves_titles['Turnover_Ratio'] = (
    total_leaves_titles['Total_Leaves']
    .div(total_leaves_titles['Total_Employees'])
    .mul(100)
    .fillna(0)
    .round()
)
total_leaves_titles['Turnover_Ratio'] = (
    total_leaves_titles['Turnover_Ratio'].map('{:.1f}%'.format)
)
total_leaves_titles

In [ ]:
total_leaves_per_dep = df.groupby('Department').agg(Total_Leaves= ('Termination Reason','count'),
                         Total_Employess = ('Employee ID' , 'nunique')
                         
                    ).reset_index()
total_leaves_per_dep

In [ ]:
px.bar(data_frame=total_leaves_per_dep , x='Department' , y=['Total_Employess','Total_Leaves'], text_auto= True , title='Total Employees and Leaves per Department',barmode='group')

In [ ]:
reasons_of_termination = df.groupby('Termination Reason')['Employee ID'].count().reset_index()
reasons_of_termination

In [ ]:
px.pie(data_frame=reasons_of_termination,names='Termination Reason' , values='Employee ID',title='Termination Reasons')

In [ ]:
total_leaves_per_Month = df.groupby(['Month_num','Salaries Month'])['Termination Reason'].count().reset_index().sort_values(by='Month_num')
total_leaves_per_Month

In [ ]:
px.line(data_frame=total_leaves_per_Month,
        x='Salaries Month',
        y='Termination Reason',
        title = 'Termination per Months',
        labels=
            {
                'Termination Reason':'Count',
                'Salaries Month' : 'Months'
            },
        text= 'Termination Reason'
        ).update_traces(textposition = 'top center')

##### Cumulative Increasement

In [ ]:
# Calculate the increasement for each employee

df=df.sort_values(['Employee ID' , 'Month_num'])
df['Monthly Increase'] = (
    df.groupby(['Employee ID'])['Additional Raise During 2026'].diff()
    .fillna(df['Additional Raise During 2026'])
)

df

In [ ]:
total_increase_per_month = (
    df.groupby(['Month_num', 'Salaries Month'])['Monthly Increase'].sum()
    .reset_index()
    .sort_values('Month_num')
)

total_increase_per_month

In [ ]:
px.bar(data_frame=total_increase_per_month,
    x='Salaries Month',
    y='Monthly Increase',
    title = 'Raises per Months',
    labels = {

        'Salaries Month' : 'Months',
        'Monthly Increase': 'Total Increasement'
   
         },
    text_auto= True)

In [ ]:
px.line(
    data_frame=total_increase_per_month,
    x='Salaries Month',
    y='Monthly Increase',
    title = 'Raises per Months',
    labels = {

        'Salaries Month' : 'Months',
        'Monthly Increase': 'Total Increasement'
   
         },
    text= 'Monthly Increase'
).update_traces(textposition = 'top center')

#### Earning Analysis

##### Totals Earnings

In [ ]:
total_bonus = df['Bonuses and Incentives'].sum()
total_additional_allowance = df['Additional Allowance'].sum()
total_other_earnings = df['Other Earnings'].sum()
total_variable_allowance = df['Variable Allowances'].sum()
Business_Trip_Allowance = df['Business Trip Allowance'].sum()
df

In [ ]:


allowance_col=[
'Bonuses and Incentives',
'Additional Allowance',
'Other Earnings',
'Variable Allowances',
'Business Trip Allowance'
]

allowance_dataframe_summary = (df[allowance_col].sum().reset_index())
allowance_dataframe_summary.columns = ['Earning type' , 'Total Amount']
allowance_dataframe_summary

px.bar(
    data_frame=allowance_dataframe_summary,
    x='Earning type',
    y='Total Amount',
    text_auto=True,
    title = 'Total Earning Amount by Type'
)

In [ ]:
total_bonus_per_department = df.groupby('Department')['Bonuses and Incentives'].sum().reset_index()
total_bonus_per_department

In [ ]:
total_trip_emp = df[df['Business Trip Allowance']>0].groupby('Department')['Employee ID'].nunique().reset_index()
total_trip_emp

In [ ]:
px.pie(
    data_frame=total_trip_emp,
    names = 'Department',
    values= 'Employee ID',
    title ='No.Trips Emplyees'
).update_traces(textinfo = 'label+value+percent').update_layout(showlegend =False)

In [ ]:
px.bar(data_frame=total_bonus_per_department,x='Department',y='Bonuses and Incentives',title='Bonus per Department',text_auto=True)

In [ ]:
total_earnings_per_department = df.groupby('Department')['Total Variable Pay'].sum().reset_index()
total_earnings_per_department

In [ ]:
total_bonus_per_month = df.groupby(['Salaries Month','Month_num'])['Bonuses and Incentives'].sum().reset_index().sort_values(by='Month_num')
total_bonus_per_month

In [ ]:
px.line(data_frame=total_bonus_per_month,x='Salaries Month',y='Bonuses and Incentives',title='Bonus per Months',text='Bonuses and Incentives',labels={'Salaries Month':'Months'}).update_traces(textposition = 'top center')

In [ ]:
total_bonus_emp_per_month = df.groupby(['Salaries Month','Month_num']).agg(
    TotalBonus = ('Bonuses and Incentives', 'sum'),
    TotalEmployees = ('Employee ID' , 'nunique')
    ).reset_index().sort_values(by='Month_num')
total_bonus_emp_per_month

In [ ]:
px.bar(
    data_frame=total_bonus_emp_per_month,
    x='Salaries Month',
    y=['TotalBonus','TotalEmployees'],
    title='Bonus per Months',
    labels={'Salaries Month':'Months'},
    barmode='group',
    text_auto= True
    )

#### Deduction

##### Totals Deductions

In [ ]:
total_absence_value = round(df['Absence Deduction Amount'].sum())
total_statutory_value = round(df['Statutory Penalty Amount'].sum())
total_administrative_penalty_value = round(df['Administrative Penalty Amount'].sum())

In [ ]:
filtered_ded_data = df[df['Total Penalties'].notna()]
filtered_ded_data

In [ ]:
total_pen_dep = filtered_ded_data.groupby(['Salaries Month' , 'Month_num']).agg(
    total_employees = ('Employee ID','nunique'),
    total_val = ('Total Penalties' , 'sum')
).reset_index().sort_values(by='Month_num')
total_pen_dep

In [ ]:
absence_ratio = (df['Absence Days'].sum()/ df['Employee ID'].nunique())
absence_ratio

In [ ]:
px.line(
    data_frame=total_pen_dep,
    x='Salaries Month',
    y='total_val',
    text='total_val',
    title= 'Total Penalties per Month'
).update_traces(textposition = 'top center')

In [ ]:
filtered_absence_data = df[df['Absence Days'].notna()]
filtered_absence_data

In [ ]:
total_employess_absence = (
                            filtered_absence_data.groupby('Department')
                            .agg(
                                Total_Employees=('Employee ID','nunique'),
                                Total_Absence_Days=('Absence Days','sum'),
                                Total_Absence_Penlty = ('Absence Penalty (Days)' , 'sum'))
                            .reset_index()
                           
)
total_employess_absence

In [ ]:
px.bar(data_frame=total_employess_absence,x='Department', y=['Total_Employees','Total_Absence_Days','Total_Absence_Penlty'] , title= 'Total Absence Employees per Department' , text_auto = True, barmode='group')

In [ ]:
total_employess_disp_pnlties = (
                            df[df['Statutory Penalty (Days)']>0].groupby('Department')
                            .agg(
                                Total_Employees=('Employee ID','nunique'),
                                Total_Days=('Statutory Penalty (Days)','sum'))
                            .reset_index()
                           
)
total_employess_disp_pnlties

In [ ]:
px.bar(data_frame=total_employess_disp_pnlties,x='Department', y=['Total_Employees','Total_Days'] , title= 'Total Statutory Penalty per Department' , text_auto = True, barmode='group')

In [ ]:
total_employess_admin_pnlties = (
                            df[df['Administrative Penalty (Days)']>0].groupby('Department')
                            .agg(
                                Total_Employees=('Employee ID','nunique'),
                                Total_Days=('Administrative Penalty (Days)','sum'))
                            .reset_index()
                           
)
total_employess_admin_pnlties

In [ ]:
px.bar(data_frame=total_employess_admin_pnlties,x='Department', y=['Total_Employees','Total_Days'] , title= 'Total Administrative Penalty per Department' , text_auto = True, barmode='group')

In [ ]:
total_employess_admin_pnlties = (
                            df[df['Administrative Penalty (Days)']>0]['Employee ID'].nunique())

total_employess_admin_pnlties

In [ ]:
# عدد الصفوف التي فيها جزاء أكبر من صفر
print(
    df[df['Administrative Penalty (Days)'] > 0].shape[0]
)

# عدد أكواد الموظفين المختلفة
print(
    df[df['Administrative Penalty (Days)'] > 0]['Employee ID'].nunique()
)

In [ ]:
penalty_employees = (
    df.loc[
        df['Administrative Penalty (Days)'] > 0,
        'Employee ID'
    ]
    .drop_duplicates()
    .sort_values()
)

print(penalty_employees.to_list())
print("Total:", len(penalty_employees))

In [ ]:
df[df['Employee ID'] == 1001]

In [ ]:
#Dduplicate 
total_penaleties_per_month = (
df.groupby(['Salaries Month','Month_num'])
['Total Penalties']
.sum()
.reset_index()
.round(2)
.sort_values(by='Month_num')
)
total_penaleties_per_month

In [ ]:
px.line(data_frame=total_penaleties_per_month,x='Salaries Month',y='Total Penalties',text='Total Penalties',title='Total Penaleties per Month').update_traces(textposition='top center')

In [ ]:
df = df.sort_values(['Salaries Month','Employee ID'])
df

In [ ]:
pd.DataFrame.to_parquet(df,"Cleaned data.parquet")